services:
  database:
    image: "postgres:latest"
    restart: always
    environment:
      POSTGRES_PASSWORD: asdf
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:

